image: node:16-buster

pipelines:
  branches:
    master:
      - step:
          name: Deploy specifications
          deployment: production
          script:
            - npx @sinetiq/api-specification-registry-cli --glob **/api-specification.json --ignore-already-registered