image: node:16-buster

pipelines:
  branches:
    master:
      - step:
          name: Deploy specifications
          deployment: production
          script:
            - npm_config_registry=https://npm.sinetiq.net npx @sinetiq/service-type-registry-cli --glob **/service-type.json --ignore-already-registered