version: "3.9"

services:
  temp-provider-1:
    container_name: temp-provider-1
    environment:
      - SR_HOST=service-registry
      - SERVICE_ADVERTISED_ADDRESS=http://temp-provider-1:8080/
      - SERVICE_ADVERTISED_PORT=8080
      - SERVICE_NAME=TempProvider1
    build: .

  temp-provider-2:
    container_name: temp-provider-2
    environment:
      - SR_HOST=service-registry
      - SERVICE_ADVERTISED_ADDRESS=http://temp-provider-2:8080/
      - SERVICE_ADVERTISED_PORT=8080
      - SERVICE_NAME=TempProvider2
    build: .

networks:
  default:
    name: sinetiq-local-cloud
    external: true # Start compose-controle-plane first
