openapi: 3.0.0
info:
  title: Temperature Sensor API HTTP(S)-JSON
  version: 1.0.0
  description: |
    This is a simple API for accessing temperature sensor data. 

    Producer: The producer in this context is the temperature sensor along with its hosting system.
    
    - GET /units: This endpoint returns a list of supported temperature units. 
    - GET /temperature: This endpoint provides the current temperature reading and associated metadata. 
    - GET /temperature/history: This endpoint provides historical temperature readings.

    Consumer: The consumer is any application or system that needs to retrieve temperature data from the producer. 

    - GET /units: A consumer would make a GET request to this endpoint to find out what units of temperature the producer supports. 
    - GET /temperature: The consumer retrieves the current temperature reading and metadata by making a GET request to this endpoint. 
    - GET /temperature/history: The consumer retrieves historical temperature readings by making a GET request to this endpoint.

    Procedure: Here is a typical interaction between a producer and a consumer:

    - The consumer system sends a GET request to the /units endpoint. The producer system receives the request and responds with a list of supported temperature units.
    - The consumer system sends a GET request to the /temperature endpoint. The producer system receives the request and responds with the current temperature reading and related metadata.
    - The consumer system sends a GET request to the /temperature/history endpoint. The producer system receives the request and responds with the historical temperature readings.

paths:
  /units:
    get:
      summary: Get supported temperature units
      x-accepts: application/json
      responses:
        '200':
          description: List of supported temperature units
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Units'
  /temperature:
    get:
      summary: Get current temperature data
      x-accepts: application/json
      responses:
        '200':
          description: Temperature data
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TemperatureData'
  /temperature/history:
    get:
      summary: Get historical temperature data
      x-accepts: application/json
      parameters:
      - description: Start date/time for the historical data
        in: query
        name: start_date
        required: true
        schema:
          format: date-time
          type: string
      - description: End date/time for the historical data
        in: query
        name: end_date
        required: true
        schema:
          format: date-time
          type: string
      responses:
        '200':
          description: Historical temperature data
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HistoricalTemperatureData'
components:
  schemas:
    Units:
      type: object
      example:
        units:
          - C
          - F
      properties:
        units:
          type: array
          items:
            type: string
    TemperatureData:
      example:
        unit: C
        machineID: Band Saw 4
        temperature: 24.1
        location: Machine Hall 12
        timestamp: 2000-01-23T04:56:07.000+00:00
      type: object
      properties:
        temperature:
          type: number
        unit:
          type: string
        location:
          type: string
        machineID:
          type: string
        timestamp:
          type: string
          format: date-time
    HistoricalTemperatureData:
      type: object
      example:
        readings:
          - unit: C
            machineID: Band Saw 4
            temperature: 24.1
            location: Machine Hall 12
            timestamp: 2000-01-23T04:56:07.000+00:00
          - unit: unit
            machineID: Band Saw 4
            temperature: 24.1
            location: Machine Hall 12
            timestamp: 2000-01-23T04:12:21.000+00:00
      properties:
        readings:
          type: array
          items:
            $ref: '#/components/schemas/TemperatureData'
