version: "3.9"

services:
  temp-provider-1:
    container_name: temp-provider-1
    environment:
      - SR_HOST=service-registry
      - SERVICE_ADVERTISED_ADDRESS=http://temp-provider-1:8080/
      - SERVICE_ADVERTISED_PORT=8080
      - SERVICE_NAME=TempProvider1
    build: sinetiq-core-application-temperature-provider/

  temp-provider-2:
    container_name: temp-provider-2
    environment:
      - SR_HOST=service-registry
      - SERVICE_ADVERTISED_ADDRESS=http://temp-provider-2:8080/
      - SERVICE_ADVERTISED_PORT=8080
      - SERVICE_NAME=TempProvider2
    build: sinetiq-core-application-temperature-provider/

  temp-consumer:
    container_name: temp-consumer
    environment:
      - CFG_SR_HOST=service-registry
      - CFG_SR_PORT=8500
    build: sinetiq-core-application-temperature-consumer/

networks:
  default:
    name: sinetiq-local-cloud
    external: true # Start compose-controle-plane first